pipeline {
    agent any

    stages {
        stage('Compile Stage') {
            steps {
                withMaven(maven : 'Maven-3.5.4') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Deployment Stage') {
            steps {
                withMaven(maven : 'Maven-3.5.4') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}